baseURL = "https://nishantgadihoke.com/"
languageCode = "en-us"
title = "Nishant Gadihoke"
author = "Nishant Gadihoke"
description = "Nishant Gadihoke is a user experience engineer based out of New Delhi. He is the co-founder and CTO of Oswald Labs, an award-winning accessibility technology company."
theme = "nishant-custom"